format: parquet
root: "data"

chains:
  - chain_id: eth2
    network: mainnet
    beacon: " "        # or provider Beacon REST base
    headers: {"x-api-key": "API KEY"}                             # e.g. {"x-api-key": "YOUR_KEY"}
    lookback_slots: 512

  - chain_id: cosmos
    network: cosmoshub
    lcd: "https://cosmos-lcd.quickapi.com"  # replace with your node/LCD
    headers: {}                             # optional
    lookback_blocks: 2000

  - chain_id: polkadot
    network: mainnet
    rpc: "wss://rpc.polkadot.io"            # or your node
    lookback_blocks: 1024
